services:
  mongo-1:
    image: mongo:5.0.7
    ports:
      - 27017:27017
    command: >
      --replSet testingSet
      --port 27017
    container_name: mongo-1
  mongo-2:
    image: mongo:5.0.7
    ports:
      - 27018:27018
    command: >
      --replSet testingSet
      --port 27018
    container_name: mongo-2
  mongo-3:
    image: mongo:5.0.7
    ports:
      - 27019:27019
    command: >
      --replSet testingSet
      --port 27019
    container_name: mongo-3
