services:
  app:
    build: .
    container_name: deploy-gradle-app
    restart: always
  nginx:
    image: nginx:mainline
    container_name: deploy-gradle-nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./deploy-gradle.conf:/etc/nginx/conf.d/default.conf
