services:
  rabbit-1:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672
    container_name: rabbit-1
    volumes:
      - ./erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
  rabbit-2:
    image: rabbitmq:3.9-management
    ports:
      - 5673:5672
      - 15673:15672
    depends_on:
      - rabbit-1
    container_name: rabbit-2
    volumes:
      - ./erlang.cookie:/var/lib/rabbitmq/.erlang.cookie

