- name: Загрузка бинарника api
  get_url:
    url: https://github.com/jusan-singularity/track-devops-systemd-api/releases/download/v0.1/api
    dest: /tmp/api
    mode: 0755
- name: Копирование api.service
  copy:
    src: "api.service"
    dest: "/lib/systemd/system/api.service"
- name: Запуск api.service
  service:
    name: api.service
    state: started
